### ISSUE TITLE
一个view里面用两个recycle-view   显示不出来

### ISSUE THREAD

**Issue by kknono** [wechat-miniprogram/recycle-view#1]
一个view里面用两个recycle-view   显示不出来
recycleId和recycleId2
以及recycleList和recycleList2

**Comment by cunjinli6** [comment]
方便贴一下你的使用的代码么？

**Comment by kknono** [comment]
create两个
// let createRecycleContext = require('../../miniprogram_npm/miniprogram-recycle-view/index.js')
      //   createRecycleContext({
      //   id: 'recycleId',
      //   dataKey: 'recycleList',
      //   page: this,
      //   itemSize: { // 这个参数也可以直接传下面定义的this.itemSizeFunc函数
      //     width: 162,
      //     height: 182
      //   }
      // }).append(bargains)

**Comment by kknono** [comment]
view代码是copy的demo，直接复制两个在同一个view上。  把recycleId和recycleList修改成不同名。
可以测试下的，确实有问题的。

**Comment by cunjinli6** [comment]
我这边尝试了没有问题，可能是2个recycle-view的其它的class有一些冲突，麻烦提供一下代码片段（https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html）我定位下

**Comment by cunjinli6** [comment]
版本0.1.1，支持一个页面多个长列表，但必须设置batch和batch-key属性：
<recycle-view batch="{{batchSetRecycleData}}" batch-key="batchSetRecycleData"></recycle-view>
  <recycle-view batch="{{batchSetRecycleData1}}" batch-key="batchSetRecycleData1"></recycle-view>
