### ISSUE TITLE
自动生成宽高 bug

### ISSUE THREAD

**Issue by xietao3** [wechat-miniprogram/recycle-view#11]
recycle-context.js
```
RecycleContext.prototype._recalculateSize = function (list) {
...
    if (offsetLeft + itemSize.width > compData.width) {
      offsetLeft = itemSize.width;
      offsetTop += sizeArray[sizeArray.length - 2].height; // 加上最后一个数据的高度
```

加上最后一个数据的高度 应该是 sizeArray.length - 1 吧？

**Comment by cunjinli6** [comment]
1. 这个不是自动生成宽高的bug
2. 这里前面有一个push的操作，所以最后一个是sizeArray.length - 2，比较绕
    **sizeArray.push(itemSize)**
    // 判断数据落到哪个方格上
    // 超过了宽度, 移动到下一行, 再根据高度判断是否需要移动到下一个方格
    if (offsetLeft + itemSize.width > compData.width) {
      offsetLeft = itemSize.width
      offsetTop += sizeArray[sizeArray.length - 2].height // 加上最后一个数据的高度
