### ISSUE TITLE
页面必须为components定义？然后会生成wx.wx.createRecycleContext() 方法？为什么我没有

### ISSUE THREAD

**Issue by SalterYu** [wechat-miniprogram/recycle-view#15]
页面必须为components定义？然后会生成wx.wx.createRecycleContext() 方法？为什么我没有

**Comment by cunjinli6** [comment]
components定义是指？
不会生成wx.wx.createRecycleContext() 方法，具体使用请参考文档https://developers.weixin.qq.com/miniprogram/dev/extended/functional/recycle-view.html
