### ISSUE TITLE
【BUG】forceUpdate时计算slot-before，slot-after无效

### ISSUE THREAD

**Issue by landn172** [wechat-miniprogram/recycle-view#16]
从代码上看forceUpdate调用reRender查询slot节点时高度是计算之后的高度`beforeSlotHeight`
![image](https://user-images.githubusercontent.com/4362412/55927009-1584c680-5c46-11e9-92a4-5fd2d4e57d0c.png)
所以此时无论如何都无法更新节点高度

**Comment by cunjinli6** [comment]
approve pull request fixed
