### ISSUE TITLE
[ BUG ] recycle-item比较高时，出现白屏

### ISSUE THREAD

**Issue by landn172** [wechat-miniprogram/recycle-view#18]
当recycle-item比较高时（大于几屏）会显现出白屏问题，如下：
![image](https://user-images.githubusercontent.com/4362412/55944682-b641a900-5c7b-11e9-9db9-4029830b4824.png)
伪代码[https://developers.weixin.qq.com/s/LFawFymr7X7Z](url)

**Comment by cunjinli6** [comment]
approve and merge pull rqeuest

**Comment by Xiaocge** [comment]
> 当recycle-item比较高时（大于几屏）会显现出白屏问题，如下：
> ![image](https://user-images.githubusercontent.com/4362412/55944682-b641a900-5c7b-11e9-9db9-4029830b4824.png)
> 伪代码[https://developers.weixin.qq.com/s/LFawFymr7X7Z](url)

同问  你解决了吗?

**Comment by landn172** [comment]
> > 当recycle-item比较高时（大于几屏）会显现出白屏问题，如下：
> > ![image](https://user-images.githubusercontent.com/4362412/55944682-b641a900-5c7b-11e9-9db9-4029830b4824.png)
> > 伪代码[https://developers.weixin.qq.com/s/LFawFymr7X7Z](url)
> 
> 同问 你解决了吗?

@im-zhangxi 我之前提交pr已经修复了。
https://github.com/wechat-miniprogram/recycle-view/pull/17/commits/6104193aabcae78ede93172aeaaf39608b108062
