### ISSUE TITLE
我这里列表的每一项都渲染了

### ISSUE THREAD

**Issue by zzxqd** [wechat-miniprogram/recycle-view#2]
![image](https://user-images.githubusercontent.com/23022401/44943380-0dcf8a80-adf8-11e8-8812-08f6a27e4aa0.png)

**Comment by zzxqd** [comment]
如图所示，不知道是不是我的写法有问题
wxml:
<recycle-view batch="{{batchSetRecycleData}}" id="recycleId">
        <recycle-item wx:for="{{recycleList}}" wx:key="id">
            <view>
                <image style='width:100px;height:100px' src="{{item.image_url}}"></image>
                {{item.idx+1}}. {{item.title}}
            </view>
        </recycle-item>
    </recycle-view>
js:
const createRecycleContext = require('miniprogram-recycle-view');
Component({
    data:{
        batchSetRecycleData:true,
        recycleList:[] 
    },
    attached:function(){
        for(let i=0;i<100;i++){
            this.data.recycleList.push({
                id:i,
                idx:i,
                image_url:'http://www.w3school.com.cn/i/eg_tulip.jpg',
                title:`这是第${i+1}项`
            })
        }
        console.log(this.data.recycleList);
        this.setData({
            recycleList:this.data.recycleList
        })
        const ctx = createRecycleContext({
            id:'recycleId',
            dataKey:'recycleList',
            page:this,
            itemSize:{
                width:162,
                height:182
            }
        });
    }
})

**Comment by cunjinli6** [comment]
不要通过setData({ recycleList:this.data.recycleList })来设置列表数据，而是通过ctx.append(recycleList)来设置。

**Comment by zzxqd** [comment]
for (let i = 0; i < 100; i++) {
            this.data.recycleList.push({
                id: i,
                idx: i,
                image_url: 'http://www.w3school.com.cn/i/eg_tulip.jpg',
                title: `这是第${i+1}项`
            })
        }
        const ctx = createRecycleContext({
            id: 'recycleId',
            dataKey: 'recycleList',
            page: this,
            itemSize: {
                width: 162,
                height: 182
            }
        });
        ctx.append(this.data.recycleList);
不行啊，老哥，没有数据
![image](https://user-images.githubusercontent.com/23022401/44943618-a1ef2100-adfb-11e8-90c9-769c3b63ce1e.png)

**Comment by zzxqd** [comment]
或者老哥能发个代码片段不，我这里看着写

**Comment by cunjinli6** [comment]
目录tools/demo里面有代码片段，跑`npm run dev`可以在最外层生成miniprogram_dev目录，用开发者工具可以跑。

**Comment by zzxqd** [comment]
似乎还是不行
![image](https://user-images.githubusercontent.com/23022401/44944109-c3540b00-ae03-11e8-96ca-f73aebf8e1f4.png)

**Comment by zzxqd** [comment]
onLoad: function () {
    var ctx = createRecycleContext({
      id: 'recycleId',
      dataKey: 'recycleList',
      page: this,
      itemSize: {
        props: 'azFirst',
        // cacheKey: 'cacheKey', // 预先缓存的key
        queryClass: 'recycle-itemsize', // 动态查询的class
        dataKey: 'recycleListItemSize', // 预先渲染的数据的wx:for绑定的变量
        // componentClass: 'recycle-list'
      },
      placeholderClass: ['recycle-image', 'recycle-text'],
      // itemSize: function(item) {
      //   return {
      //     width: 195,
      //     height: item.azFirst ? 130 : 120
      //   }
      // },
      // useInPage: true
    })
    let list = [];
    for (let i = 0; i < 100; i++) {
      list.push({
        id: i,
        idx: i,
        image_url: 'http://www.w3school.com.cn/i/eg_tulip.jpg',
        title: `这是第${i+1}项`
    })
    }
    this.ctx = ctx;
    this.ctx.append(list);
  }

**Comment by zzxqd** [comment]
在你的代码上通过append来增加列表还是会全部都渲染

**Comment by cunjinli6** [comment]
我看你给的是56条，总数据是100条，所以没有渲染所有数据？目前是会渲染多几屏的数据的。

**Comment by zzxqd** [comment]
是的，我这里没注意，可能是我高度定的太低了，所以渲染的数据会多点，多谢老哥
