### ISSUE TITLE
开发者工具没有报错，ios和安卓机报height undefined,无法显示页面

### ISSUE THREAD

**Issue by chenchao6** [wechat-miniprogram/recycle-view#22]
ios和安卓渲染页面时, recycle-context.js 报错height undefined
 `offsetTop += sizeArray[sizeArray.length - 2].height`

需要改成：
```
if (sizeArray.length >= 2 ) {
        offsetTop += sizeArray[sizeArray.length - 2].height || 0 // 加上最后一个数据的高度
 } else {
        offsetTop += itemSize.height
 } 
```
就能正常运行了

**Comment by cunjinli6** [comment]
你是用仓库demo跑报错么?如果不是，麻烦提供下https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html

**Comment by cunjinli6** [comment]
0.1.1 fixed
