### ISSUE TITLE
实例化失败，不能 append 或者 splice等方法

### ISSUE THREAD

**Issue by nightstarw** [wechat-miniprogram/recycle-view#25]
![image](http://ww3.sinaimg.cn/large/006tNc79ly1g5zba3xokdj30r805cwel.jpg)
![image](http://ww1.sinaimg.cn/large/006tNc79ly1g5zbbisfujj30ot0470t0.jpg)
报错代码如上。
跟demo对比返现 图一 的 complete 为 null
茫然，求助。

**Comment by nightstarw** [comment]
好啦 知道了

**Comment by qianlonggg** [comment]
> 好啦 知道了

这个是啥问题

**Comment by nightstarw** [comment]
> > 好啦 知道了
> 
> 这个是啥问题

生命周期问题，应该实例化完成再调用。我没有实例化完成就调用了。

**Comment by qianlonggg** [comment]
OK

> > > 好啦 知道了
> > 
> > 
> > 这个是啥问题
> 
> 生命周期问题，应该实例化完成再调用。我没有实例化完成就调用了。

OK
