### ISSUE TITLE
禁用recycle-view组件的滚动

### ISSUE THREAD

**Issue by xszi** [wechat-miniprogram/recycle-view#26]
如果我要实现小程序控制scroll-view水平或纵向的滚动，有这样一个场景，出现弹窗蒙层时，不让蒙层之下的组件滚动，原来scroll-view可以设置true或false来实现，那现在这个recycle-view应该怎么来实现？

**Comment by cunjinli6** [comment]
新增了scroll-y属性，可以禁止scroll-view滚动
