### ISSUE TITLE
recycle-view中的swiper每次更新导致recycle-view滑回顶部

### ISSUE THREAD

**Issue by zealforbeing** [wechat-miniprogram/recycle-view#27]
如题，需要在长列表顶部嵌套一个自动更新的swiper，但每次swiper更新都会导致recycle-view滚回到顶部，求解决方案

**Comment by cunjinli6** [comment]
recycle-view重新渲染了？可以记录一下recycle-view的位置（recycle-context里面的getScrollTop函数），下次回复到改位置。

**Comment by zealforbeing** [comment]
我设置数据的问题，将两个数据分开更新就可以了，感谢回复
