### ISSUE TITLE
为什么需要基础库2.2.2?

### ISSUE THREAD

**Issue by ChenHuiMing44** [wechat-miniprogram/recycle-view#28]
大致看过遍代码好像没有发现需要2.2.2才需要使用的api， 将代码下下来后有自己在1.9.X上尝试，没遇见报错，可以直接在 1.9以上办的版本使用么

**Comment by cunjinli6** [comment]
npm包的方式是2.2.1开始支持的。主要是这个点。

**Comment by ChenHuiMing44** [comment]
就是我把代码下载下来后可以在1.9.X上使用的是吧
