### ISSUE TITLE
dataKey能否改为支持一个字符串数组？

### ISSUE THREAD

**Issue by zzxqd** [wechat-miniprogram/recycle-view#3]
我现在在做一个瀑布流的组件，想集成这个recycle-view，就有一点问题了，我的思路是通过在recycle-view下多列布局，每列放置一个recycle-item循环的组件，然后每次去向最短的那一列增加数据。
实际做的时候发现createRecycleContext里的datakey似乎不支持多个，有办法解决么？
或者能否给个修改的建议呢

**Comment by zzxqd** [comment]
或者我通过createRecycleContext为每一列都创建一个ctx，然后这些实例对象有着同一个recycle-view
这样现在的代码是否支持

**Comment by cunjinli6** [comment]
创建多个recycle-view即可？

**Comment by zzxqd** [comment]
不好吧，这个组件不是一个recycle-view就是一个scroll-view么，我如果每列放一个的话那就是多个scroll-view并排，用户在滑动的时候只会让其中一个scroll-view滑动吧

**Comment by zzxqd** [comment]
每个ctx共享一个recycle-view,各自拥有recycle-list这个我试过了，只能有一列能有数据，其他列通过append()无法添加，
如果给recycle-view组监听scroll事件让其他列都跟随scroll而滚动会不会出现滚动滞后影响用户体验呢

**Comment by cunjinli6** [comment]
瀑布流的需求我这边考虑一下。

**Comment by zzxqd** [comment]
多谢老哥👍
