### ISSUE TITLE
文档内容前后不一致，希望明确一下placeholderClass等属性目前的状况

### ISSUE THREAD

**Issue by jjyyxx** [wechat-miniprogram/recycle-view#33]
在 280d78f 版本中，文档删去了具体描述“自动生成高度”功能的部分，而文档其他部位仍有提及。请问：
1. 自动生成高度以及自动生成placeholder的功能现在还被支持吗？
2. 如果仍然支持，为什么要从文档中删去？
3. 如果不再支持，还有方法比较方便地生成placeholder吗？

希望官方统一一下文档。

**Comment by cunjinli6** [comment]
自动生成高度还有点bug，可以认为暂时不支持，文档已去掉fix
