### ISSUE TITLE
抖动问题

### ISSUE THREAD

**Issue by yf01** [wechat-miniprogram/recycle-view#4]
滚动的过程中会有抖动是innerBeforeHeight值计算不准还是滚动过程中改变top值本身就会出现抖动呢？

**Comment by yf01** [comment]
数据跳动的问题是不是  beginIndex endIndex差值跟上次的不一样导致的呢？
这个问题是怎么解决的呢？

**Comment by cunjinli6** [comment]
一般是itemSize的width和height和recycle-item设置的width和height不一致导致的！

**Comment by yf01** [comment]
当top修改，beginIndex endIndex之间的数据值重新渲染，从底部瞬间顶到当前的滚动位置。这个过程会闪烁一下？

**Comment by cunjinli6** [comment]
这种情况确实会闪烁一下，是由于重新渲染可视区域引起的。

**Comment by li2go** [comment]
😄
