### ISSUE TITLE
好像没有一个正确清除数组的方法

### ISSUE THREAD

**Issue by huhai122** [wechat-miniprogram/recycle-view#47]
有需求是通过tab去渲染不同的list 用的其实还是一个组件 组件一直没有销毁 动态的修改list数据
尝试了用update和splice都没有办法清除数组

**Comment by cunjinli6** [comment]
有[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)么

**Comment by huhai122** [comment]
![image](https://user-images.githubusercontent.com/34016514/66451631-ee417180-ea8f-11e9-9fc2-995d40dffb36.png)
比如有个list是 [1,2,3] 切换tab以后 list是[2,3]
箭头指向的这个循环体还是循环length是3的数组 结果只修改了1和2   第3项并没有修改 用的update方法

**Comment by huhai122** [comment]
看了下代码 好像append不能做到更新数组的需求
目前是通过splice先去清空原数组的长度 然后在callback中 调用append去做的

**Comment by huhai122** [comment]
想请教一下 checkComp这个方法的作用是什么 我这里selectComponent组件 切换tab一直会走else 报the recycle-view correspond to this context is detached, pls create another RecycleContext 但是好像也没什么影响

**Comment by cunjinli6** [comment]
splice的用法和Array的splice一样，可以删除的同时新增内容

**Comment by cunjinli6** [comment]
> 想请教一下 checkComp这个方法的作用是什么 我这里selectComponent组件 切换tab一直会走else 报the recycle-view correspond to this context is detached, pls create another RecycleContext 但是好像也没什么影响

销毁recycle-view的同时也把 recycleContext

**Comment by wotoutengleha** [comment]
楼主最后怎么解决的
