### ISSUE TITLE
求实现一个案例

### ISSUE THREAD

**Issue by ChinaJiu** [wechat-miniprogram/recycle-view#5]
作者可否再把文档写的详细一些，再建一个仓库实现一个渲染1000张图片或者视频小程序的案例，感谢！！！！

**Comment by cunjinli6** [comment]
tools目录下面有一个案例，使用方法如下：
1. clone仓库代码下来，执行npm i && npm run dev
2. 通过开发者工具创建项目，目录为miniprogram_dev

**Comment by ChinaJiu** [comment]
好的明白了

**Comment by loneyclown** [comment]
`rm -f miniprogram_dev/project.config.json && gulp dev --develop`
'rm' 不是内部或外部命令，也不是可运行的程序，而且我下载下来的目录里面也没有miniprogram_dev目录呀。
我是直接下载的`recycle-view-master`。。。

**Comment by GHwangzehua** [comment]
当上拉加载更多以后，慢慢活动页面到最顶端会发现数据会错乱；（比如id为49的已经滑动到最下面了；但是继续滑动还会出现一个id为49的；而且第一个渲染出来的列表项id也不是1了）

**Comment by cunjinli6** [comment]
> `rm -f miniprogram_dev/project.config.json && gulp dev --develop`
> 'rm' 不是内部或外部命令，也不是可运行的程序，而且我下载下来的目录里面也没有miniprogram_dev目录呀。
> 我是直接下载的`recycle-view-master`。。。

首次先跑下tnpm i && gulp dev --develop

**Comment by cunjinli6** [comment]
> 当上拉加载更多以后，慢慢活动页面到最顶端会发现数据会错乱；（比如id为49的已经滑动到最下面了；但是继续滑动还会出现一个id为49的；而且第一个渲染出来的列表项id也不是1了）

用法上有点问题？这个issue close了，麻烦重新新建一个issue，提供下[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)
