### ISSUE TITLE
怎么调用transformRpx方法？

### ISSUE THREAD

**Issue by chengkaii** [wechat-miniprogram/recycle-view#54]
`var ctx = createRecycleContext({
      id: 'recycleId',
      dataKey: 'recycleList',
      page: this,
      itemSize: this.itemSizeFunc
    })

    ctx.append(that.data.newList)
    this.ctx = ctx

  },
  itemSizeFunc: function(item, idx) {

    var that = this;
    const ctxx = this.ctx
    return {
      width: ctxx.transformRpx(300),
      height: 182
    }
  },
`

调用transformRpx方法必须有ctx实体，但是得到ctx必须知道itemSize，如果itemSizeFunc需要设置rpx单位的大小，那不是矛盾了，也就是说刚开始设置的itemSize只能是px单位的？

**Comment by huhai122** [comment]
const transformRpx = require('./utils/transformRpx.js').transformRpx
我是这么用的

**Comment by Marla62** [comment]
'./utils/transformRpx.js'是从哪里来的

**Comment by chengkaii** [comment]
<img width="1235" alt="WX20200610-142632@2x" src="https://user-images.githubusercontent.com/10311041/84234288-895e7f80-ab26-11ea-9a89-baa351c85344.png">

**Comment by chengkaii** [comment]
我眼瞎了。。
