### ISSUE TITLE
实际使用过程中发现白屏，闪烁问题很严重

### ISSUE THREAD

**Issue by callmenero** [wechat-miniprogram/recycle-view#56]
如上，实际使用过程中发现白屏，闪烁问题很严重，完全没法在项目中应用，不知道是不是我的使用姿势不对，恳请官方提供一个使用Demo，万分感激

**Comment by callmenero** [comment]
组件好像完全没法使用

**Comment by snowwolflibo** [comment]
@callmenero 
我把demo整理了一下，也修复了白屏闪烁问题，你可以试一下：https://github.com/snowwolflibo/mini-program-recycle-view

**Comment by callmenero** [comment]
好的，万分感激，我看看



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neo Li"<notifications@github.com&gt;; 
发送时间: 2019年11月25日(星期一) 上午10:05
收件人: "wechat-miniprogram/recycle-view"<recycle-view@noreply.github.com&gt;; 
抄送: "ygtu"<1125548362@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [wechat-miniprogram/recycle-view] 实际使用过程中发现白屏，闪烁问题很严重 (#56)




@callmenero
 我把demo整理了一下，也修复了白屏闪烁问题，你可以试一下：https://github.com/snowwolflibo/mini-program-recycle-view

**Comment by asmallkite** [comment]
@snowwolflibo 请问你修改了什么？
