### ISSUE TITLE
长列表组件长度在某些机型下会超出设定值

### ISSUE THREAD

**Issue by Kerminate** [wechat-miniprogram/recycle-view#6]
![image](https://user-images.githubusercontent.com/26789139/48839642-16b47480-edc7-11e8-9566-5ec14208013f.png)
源码里 默认设置了长列表的宽度是屏幕的宽度，如果这个长列表实际宽度小于屏幕宽度，那么在有些机型下（荣耀V10）它的宽度会变成屏幕宽度，导致左右可滑动。
![image](https://user-images.githubusercontent.com/26789139/48839695-3c417e00-edc7-11e8-8293-4d14bee50f8e.png)

**Comment by cunjinli6** [comment]
实际宽度小于屏幕宽度，不应该设置为屏幕宽度，可通过<recycle-view width="{{width}}"></recycle-view>设置实际宽度。
