### ISSUE TITLE
以下文件没有被打包上传：

### ISSUE THREAD

**Issue by kknono** [wechat-miniprogram/recycle-view#7]
以下文件没有被打包上传：
· node_modules/miniprogram-recycle-view/.babelrc
· node_modules/miniprogram-recycle-view/.eslintrc.js
· node_modules/miniprogram-recycle-view/LICENSE
· node_modules/miniprogram-recycle-view/README.md
· node_modules/miniprogram-recycle-view/gulpfile.js
· node_modules/miniprogram-recycle-view/package.json
· node_modules/miniprogram-recycle-view/images/js.png
· node_modules/miniprogram-recycle-view/images/recycle-view.bmpr
· node_modules/miniprogram-recycle-view/images/recycle-view.png
· node_modules/miniprogram-recycle-view/images/wxml.png
· node_modules/miniprogram-recycle-view/miniprogram_dist/index.js
· node_modules/miniprogram-recycle-view/miniprogram_dist/recycle-item.js
· node_modules/miniprogram-recycle-view/miniprogram_dist/recycle-item.wxml
· node_modules/miniprogram-recycle-view/miniprogram_dist/recycle-item.json
· node_modules/miniprogram-recycle-view/miniprogram_dist/recycle-item.wxss
· node_modules/miniprogram-recycle-view/miniprogram_dist/recycle-view.js
· node_modules/miniprogram-recycle-view/miniprogram_dist/recycle-view.json
· node_modules/miniprogram-recycle-view/miniprogram_dist/recycle-view.wxml
· node_modules/miniprogram-recycle-view/miniprogram_dist/recycle-view.wxss
· node_modules/miniprogram-recycle-view/src/index.js
· node_modules/miniprogram-recycle-view/src/recycle-item.js
· node_modules/miniprogram-recycle-view/src/recycle-item.json
· node_modules/miniprogram-recycle-view/src/recycle-item.wxml
· node_modules/miniprogram-recycle-view/src/recycle-item.wxss
· node_modules/miniprogram-recycle-view/src/recycle-view.js
· node_modules/miniprogram-recycle-view/src/recycle-view.wxml
· node_modules/miniprogram-recycle-view/src/recycle-view.json
· node_modules/miniprogram-recycle-view/src/recycle-view.wxss
· node_modules/miniprogram-recycle-view/src/utils/recycle-context.js
· node_modules/miniprogram-recycle-view/src/utils/recycle-data.js
· node_modules/miniprogram-recycle-view/src/utils/transformRpx.js
· node_modules/miniprogram-recycle-view/src/utils/viewport-change-func.js
· node_modules/

开发工具不能打包

**Comment by JuneAndGreen** [comment]
node_modules 下是不被上传的，请按照小程序的 npm 文档，构建到 miniprogram_npm 中：

https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html
