### ISSUE TITLE
useInPage=false, 使用tabBar时，默认高度错误

### ISSUE THREAD

**Issue by youngyou** [wechat-miniprogram/recycle-view#8]
useInPage=false, 使用tabBar时，初始获取到的windowHeight不包括tabBar高度，当路由跳转到recycle-view页面，且本页面为非tabbar页面时，底部会有空白.
建议在页面生命周期起始时获取windowHeight
 
![2018-11-30 11 10 23](https://user-images.githubusercontent.com/8455667/49297219-33525a00-f4f5-11e8-8366-a4c8abaace94.png)

**Comment by cunjinli6** [comment]
由于是设置组件的高度默认值，必须在生命周期开始之前设置。
你可以重新设置一下高度<recycle-view height="{{windowHeight}}"></recycle-view>，而不使用默认的高度。
