### ISSUE TITLE
通过scroll-to-index滚动到指定位置时，会白屏

### ISSUE THREAD

**Issue by yourfriendyang** [wechat-miniprogram/recycle-view#9]
通过scroll-to-index滚动到指定位置时，较大概率会白屏，用手再稍微滚动一点后才能正确显示

**Comment by yourfriendyang** [comment]
var THROTTLE_DISTANCE = 2000; // 超过这个的滚动距离必须要抛弃掉
经查，是由上述限制引起的，感觉这里是不是应该对于scroll-to-index触发的滚动，要忽略这个限制，不然长列表长距离必然会出问题。我暂时先调用一次forceUpdate来解决这个问题了

**Comment by cunjinli6** [comment]
问题已收到，感谢你的反馈。
